sampletime: 2
kcd:
  - kcd/gm_global_a_hs.kcd
  - kcd/gm_global_a_ls.kcd

graph_default:
  x_axis_type: datetime
  x_axis_label: "Time"
  tools: "pan,wheel_zoom,box_zoom,reset,box_select"

graphs:
  driver:
    title: "Driver Input"
    x_axis_label: "Time"
    y_axis_label: "Inputs"
    series:
      "Throttle(%)":
        x: 'time'
        y: 'accelerator_actual_position'
        color: 'green'
        type: line_cross
      "Steering (Deg)":
        x: 'time'
        y: 'steering_wheel_angle'
        color: 'orange'
        type: line_cross
      "Brake Position(%)":
        x: 'time'
        y: 'platform_brake_position'
        color: 'purple'
        type: line_cross

  speed:
    title: "Speed"
    x_axis_label: "Time"
    y_axis_label: "Speed (kph)"
    x_range: 0
    series:
      "Speed":
        x: 'time'
        y: 'speed_average_non_driven_valid'
        color: 'green'
        type: line_cross

  rpms:
    title: "Engine Speed"
    y_axis_label: "RPM"
    x_axis_label: "Time"
    x_range: 0
    series:
      "RPM":
        x: 'time'
        y: 'engine_speed'
        color: 'red'
        type: line_cross

  accelquad:
    title: "Acceleration Quadrant"
    x_axis_label: "Lateral(g)"
    x_axis_type: linear
    y_axis_label: "Longitudinal(g)"
    series:
      "Acceleration":
        x: 'lat_g'
        y: 'long_g'
        color: 'red'
        type: circle

  transmission:
    title: "Transmission"
    x_axis_label: "Time"
    y_axis_label: "Gear"
    x_range: 0
    series:
      "Commanded Gear":
        x: 'time'
        y: 'transmission_commanded_gear'
        color: 'red'
        type: line_cross
      "Estimated Gear":
        x: 'time'
        y: 'transmission_estimated_gear'
        color: 'green'
        type: line_cross
      "Clutch Engaged":
        x: 'time'
        y: 'top_clutch_travel'
        color: 'blue'
        type: line_cross
      "Skip Shift Active":
        x: 'time'
        y: 'skip_shift_active'
        color: 'orange'
        type: line_cross

  braking:
    title: "ChassisInfo"
    x_axis_label: "Time"
    y_axis_label: "Status"
    x_range: 0
    series:
      "Brakes":
        x: 'time'
        y: 'brake_pedal_driver_applied_pressure_detected'
        color: 'red'
        type: line_cross
      "ABS":
        x: 'time'
        y: 'abs_active'
        color: 'blue'
        type: line_cross
      "VDCS":
        x: 'time'
        y: 'vdcs_understeer_active'
        color: 'cyan'
        type: line_cross

  temperatures:
    title: "Temperatures"
    x_axis_label: "Time"
    y_axis_label: "Temp (C)"
    x_range: 0
    series:
      "Engine Coolant Temp":
        x: 'time'
        y: 'engine_coolant_temperature'
        color: 'red'
        type: line_cross
      "Intake Temperature":
        x: 'time'
        y: 'engine_intake_temperature'
        color: 'cyan'
        type: line_cross
      "Trans Oil Temp":
        x: 'time'
        y: 'trans_oil_temp'
        color: 'orange'
        type: line_cross

  boost:
    title: "Boost"
    x_axis_label: "Time"
    y_axis_label: "Boost(%)"
    x_range: 0
    series:
      "Boost":
        x: 'time'
        y: 'boost_pressure_indication'
        color: 'blue'
        type: line_cross

  map:
    title: "Map"
    x_axis_type: linear
    y_axis_label: "Latitude"
    series:
      "GPS":
        x: 'x_webmercator'
        y: 'y_webmercator'
        color: 'red'
        type: line_cross


